# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_home_goals', models.BigIntegerField(blank=True, null=True)),
                ('team_away_goals', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('points', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
    ]
