# Generated by Django 2.0.5 on 2018-05-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='still_active',
            field=models.BooleanField(default=True),
        ),
    ]
