# Generated by Django 2.0.5 on 2018-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=64, null=True)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'In progress'), (1, 'Awaiting approval'), (2, 'Publishing')], default=0)),
                ('release_start', models.DateField(null=True)),
                ('release_end', models.DateField(null=True)),
            ],
        ),
    ]

